### ISSUE TITLE
您好，请问这个数据集有吗？

### ISSUE THREAD

**Issue by bsmwrq** [LongFei1234/jittor-Benchmark-a_scene_generator_based_on_GauGAN#1]

**Comment by LongFei1234** [comment]
您好，这里是计图人工智能挑战赛的[比赛网址链接](https://www.educoder.net/competitions/index/Jittor-3)
您可以从“赛题说明”——“赛道一”的内容中找到训练集的下载链接
您可以从“评测数据”——“赛道一”的内容中找到测试集的下载链接

**Comment by bsmwrq** [comment]
谢谢，辛苦了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LongFei1234/jittor-Benchmark-a_scene_generator_based_on_GauGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月6日(星期三) 晚上9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LongFei1234/jittor-Benchmark-a_scene_generator_based_on_GauGAN] 您好，请问这个数据集有吗？ (Issue #1)





 
您好，这里是计图人工智能挑战赛的比赛网址链接
 您可以从“赛题说明”——“赛道一”的内容中找到训练集的下载链接
 您可以从“评测数据”——“赛道一”的内容中找到测试集的下载链接
